### PR TITLE
Get Posts By Github Repo function added

### PR DESCRIPTION
**Pull request by adasq**
Hey,

I would love to use your project, but it lacks API function required by my project. I added `getPostsByGithubProject` which returns set of utopian posts related to specific github project.

In order to do so, we need to ash github api firstly, to retrive id by repo name.

usage examples:

```js
utopian.getPostsByGithubProject('eSteemApp/esteem', {
    type: 'development'
}).then(result => console.log(result))
```

or: 

```js
utopian.getPostsByGithubProject('utopian-io/utopian-api-npm').then(result => console.log(result))
```

Hope to hear from you.

### CODE REVIEW

**Comment by wehmoen** [comment]
This package is intended to work without any 3rd pary dependencies. Please remove the request package.

**Comment by adasq** [comment]
Fixed.

**Comment by wehmoen** [comment]
Please resolve the merge conflicts withing the next 4 days. Otherwise this PR will be closed.

**Comment by adasq** [comment]
I'm sorry I have missed a conflict notification. I increased a test timeout, as it's failing with poor connection environments. I hope it's a no big deal.

Cheers.

**Pull request merged**
